name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # === Stage: Checkout ===
      - name: Checkout repository
        uses: actions/checkout@v3

      # === Stage: Build Maven Project ===
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build with Maven
        run: mvn clean package -DskipTests

      # === Stage: Build Docker Image ===
      - name: Build Docker image
        run: docker build -t sample-app .

      # === Stage: Run Docker Container ===
      - name: Run Docker container
        run: docker run --rm sample-app

      # === Post Success ===
      - name: Post Success Message
        if: success()
        run: echo "Pipeline completed successfully!"

      # === Post Failure ===
      - name: Post Failure Message
        if: failure()
        run: echo "Pipeline failed."
